"""create refund requests table

Revision ID: 9495bdfe78c0
Revises: dc79648096fc
Create Date: 2026-05-20 18:01:54.650763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9495bdfe78c0'
down_revision: Union[str, Sequence[str], None] = 'dc79648096fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_refund_requests_idempotency_key', 'refund_requests', ['idempotency_key'], unique=False)
    op.create_index('ix_refund_requests_order_id', 'refund_requests', ['order_id'], unique=False)
    op.create_index('ix_refund_requests_status', 'refund_requests', ['status'], unique=False)
    op.create_index('ix_refund_requests_user_id', 'refund_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refund_requests_user_id', table_name='refund_requests')
    op.drop_index('ix_refund_requests_status', table_name='refund_requests')
    op.drop_index('ix_refund_requests_order_id', table_name='refund_requests')
    op.drop_index('ix_refund_requests_idempotency_key', table_name='refund_requests')
    op.drop_table('refund_requests')
    # ### end Alembic commands ###
